project:
  title: "Statistics lectures"
  type: default
editor: source

format:
  revealjs:
    background-image: url("https://profandyfield.github.io/statistics_lectures/shared_media/images/slide_background_main.jpg")
    theme:
      - brand
      - ds2_theme.scss
      - white
    template-partials:
      - /helpers/title-slide.html
    title-slide-attributes:
      data-background-image: shared_media/images/slide_background_title.jpg
      data-background-size: 100%
      data-background-position: center
      data-background-opacity: "1"
    slide-number: true
    fig-align: center
    chalkboard:
      buttons: false
    preview-links: auto
    code-fold: false
    code-overflow: wrap
    highlight: "kate"
    revealjs-plugins:
      - editable
    show-notes: false
    pdf-separate-fragments: false

