---
title: "Statistics lectures"
author: "Andy P. Field"
format: 
  html:
    title-block-banner: "#7B67A2"
    toc: true
    toc_float: true
    embed-resources: true
    theme: [helpers/discovr_access.scss]
---

## Discovering Statistics lectures

1. [Statistical Models: What are they and why do we need them?](ds_01_statistical_models/ds_models.html)
2. [Interpreting Models: Parameter estimates, confidence intervals and *p*-values](ds_02_interpretation/ds_interpretation.html) 
3. [Model fit and multiple predictors](ds_03_fit/ds_fit.html)
4. [The beast of bias](ds_04_bias/ds_bias.html)
5. [Mediation](ds_05_mediation/ds_mediation.html)
6. [Categorical predictors: comparing means](ds_06_means/ds_means.html)
7. [Contrast coding]()
8. [Adjusting means]()
9. [Factorial designs]()
10. [Repeated measures designs]()
11. [Mixed designs]()

## An adventure in Statistics lectures

1. [Statistical Models: What are they and why do we need them?](ds_01_statistical_models/ds_models.html)
2. [Interpreting Models: Parameter estimates, confidence intervals and *p*-values](ds_02_interpretation/ds_interpretation.html) 
3. [Model fit and multiple predictors](ds_03_fit/ds_fit.html)
4. [The beast of bias](ds_04_bias/ds_bias.html)
5. [Bayesian approaches](ais_05_bayes/ais_bayes.html)
6. [Categorical predictors: comparing means](ds_06_means/ds_means.html) 
7. [Contrast coding]() 
8. [Adjusting means]() 
9. [Factorial designs]()
10. [Multilevel models (Part I)](ais_11_mlm/mlm.html)
11. [Multilevel models (Part II)](ais_11_mlm/mlm.html)
12. [Repeated measures as a multilevel model](ais_12_rm_designs/repeated_measures_lme.html) 
13. [Growth models]() 
14. [Categorical outcomes]()

## Misc

- [Getting started in R, RStudio and R Markdown](ais_00_r/ais_r.html)
- [Meta-analysis: overview]()
- [Meta-analysis: data]()
